### ISSUE TITLE
DescribeAutoScalingGroups返回异常

### ISSUE THREAD

**Issue by hiscal2015** [TencentCloud/tencentcloud-sdk-go#28]
代码如下：

```
	desAsgRequest := asg.NewDescribeAutoScalingGroupsRequest()
	desAsgRequest.AutoScalingGroupIds = append(desAsgRequest.AutoScalingGroupIds, common.StringPtr("as-xxxx"))
	desAsgRequestResponse, err := client.DescribeAutoScalingGroups(desAsgRequest)
	log.Printf("[DEBUG] client.DescribeAutoScalingGroups response: %s", desAsgRequestResponse.ToJsonString())
	if _, ok := err.(*errors.TencentCloudSDKError); ok {
		return fmt.Errorf("An API error has returned: %s", err)
	}
	if err != nil {
		log.Printf("[DEBUG] checkpoint api err")
		return err
	}
```

经调试，返回err:
```
 json: cannot unmarshal number into Go struct field AutoScalingGroup.ProjectId of type []*uint64
```

详细返回：
```
2019/02/13 16:00:46 response.go:73: Unexpected Error occurs when parsing API response
{
    "Response": {
        "AutoScalingGroupSet": [
            {
                "LaunchConfigurationId": "asc-dt3qub0j",
                "ForwardLoadBalancerSet": [],
                "LoadBalancerIdSet": [],
                "InstanceCount": 0,
                "DesiredCapacity": 0,
                "AutoScalingGroupStatus": "NORMAL",
                "AutoScalingGroupId": "asg-b5zq0bax",
                "EnabledStatus": "ENABLED",
                "ProjectId": 0,
                "RetryPolicy": "IMMEDIATE_RETRY",
                "AutoScalingGroupName": "test2",
                "InServiceInstanceCount": 0,
                "DefaultCooldown": 300,
                "MinSize": 0,
                "MaxSize": 0,
                "VpcId": "vpc-do87578g",
                "LaunchConfigurationName": "test2",
                "CreatedTime": "2019-02-13T05:55:19Z",
                "SubnetIdSet": [
                    "subnet-1xefiwsx",
                    "subnet-2tvqhvrt"
                ],
                "TerminationPolicySet": [
                    "OLDEST_INSTANCE"
                ],
                "ZoneSet": []
            }
        ],
        "TotalCount": 1,
        "RequestId": "b89cef66-8bec-4b17-956d-2352272f39a3"
    }
}
panic: json: cannot unmarshal number into Go struct field AutoScalingGroup.ProjectId of type []*uint64

goroutine 1 [running]:
main.main()
        ./test.go:35 +0x5a9
```

请求协助，谢谢。

**Comment by hiscal2015** [comment]
找到原因了，已提交pull request：https://github.com/TencentCloud/tencentcloud-sdk-go/pull/29

**Comment by zqfan** [comment]
3.0.48已修复这个问题
